en:
  greeting_message: "Hello"
  farewell_message: "Bye"
  start_menu_message: "<i>Choose that you want</i>"
  thanks: "Thanks"
  sign_in: "Sign in"
  more_actions: "More actions"
  settings: "Settings"
  settings_list: "Settings"
  hide_menu: "[Hide menu]"
  add_user_login: "Enter <b>LOGIN</b> (email/phone)"
  add_user_password: "Enter <b>PASSWORD</b>"
  new_password_condition: "The new password must be at least 6 characters long"
  not_correct_email: "This is not email."
  error: "Error"
  auth_failed: "Not correct email or password."
  try_again: "Try again"
  greetings: "Welcome"
  auth_success: "Authorization succeed"
  not_correct_data_input: "Not correct data input."
  teachbase: "Teachbase"
  retry: "Retry connection"
  cs_active: "active"
  cs_archived: "archived"
  average_score_percent: "Summary average score"
  total_time_spent: "Total time spent on learning"
  courses: "Courses"
  hour: "h."
  minutes: "min."
  profile_state: "Your profile progress"
  profile: "Profile"
  user_profile: "Profile"
  need_auth: "You must be authorized"
  for_profile: "for profile"
  stage_empty: "It's just empty now"
  enter: "Authorization"
  cs_list: "Courses list"
  show_course_list: "Show course list"
  course: "Course"
  cs: "Course"
  open: "Open"
  course_results: "Results"
  deadline: "Deadline"
  progress: "Learning progress"
  started_at: "Started at"
  success: "Successful"
  status: "Complete status"
  state: "State"
  success_true: "Success"
  success_false: "Failed"
  status_active: "Active"
  status_archived: "Archived"
  section: "Section"
  section2: "section"
  section_show_hint: "For example *[id:1]* - will open section №1"
  in: "in"
  information: "Information"
  course_sections: "Sections"
  update_data: "Update"
  updating_data: "Updating data. Please wait"
  updating_success: "Updated succeful"
  section_unable: "Do previosly sections first"
  section_delayed: "Section is unable. Will be open at:"
  section_unpublish: "This section is unpublish now"
  material: "Material"
  empty: "Nothing is here"
  cs_update: "Update courses list"
  sign_out: "Exit"
  unexpected_error: "Unexpected error"
  scenario: "Study mode"
  base: "Base"
  localization: "Localization"
  show_all: "All"
  show_avaliable: "Avaliable"
  show_unvaliable: "Unvaliable"
  show_all_sections: "All sections"
  show_avaliable_sections: "Avaliable sections"
  show_unvaliable_sections: "Unvaliable sections"
  from: "from"
  avaliable: "Avaliable"
  section3: "sections"
  find_by_query_num: "Find by №"
  find_by_query_num_sections: "Find section by №"
  enter_the_number: "Enter the number"
  edit: "Edit"
  editing_settings: "Editing settings"
  editted: "Editted"
  standart_learning: "Standart"
  marathon: "Marathon"
  ru: "Russian"
  en: "English"
  choose_localization: "Choose localization"
  choose_scenario: "Choose study mode"
  back: "Back"
  forward: "Forward"
  show_more: "Show more"
  courses2: "courses"
  materials: "Material"
  tasks: "Task"
  quizzes: "Quiz"
  quiz: "Quiz"
  scorm_packages: "SCORM"
  content: "Content"
  open: "Open"
  back_to: "Back to"
  approve: "Approve"
  view: "View"
  viewed: "Viewed"
  send: "Send"
  answer: "Answer"
  task: "Task"
  attachments: "Attachments"
  enter_your_answer: "Send to the bot what you want. It can be anything - text, photo, video, audio, document (5 MB)"
  confirm_action: "Confirm this action"
  accept: "Accept"
  decline: "Decline"
  accepted: "Accepted"
  declined: "Declined"
  show: "Show"
  answers: "Answers"
  comments: "Comments"
  comment: "Comment"
  commented: "Commented"
  stop: "Stop"
  ready: "Ready"
  enter_your_next_answer: "Continue to send messages to the bot. Or click on the button in the menu"
  checking: "Checking"
  undefined_action: "Oops! Don't know how to do it at now"
  undefined_text: "Oh! I don't understand what is needed ... Rephrase?"
  undefined_contact: "The settings for communicating with this contact have not yet been set."
  undefined_file: "Oh file. Thanks, but I don't need it yet :)"
  battle: "Battle"
  description: "Description"
  categories: "Categories"
  questions_count: "Questions count"
  passing_grade: "Passing grade"
  attempts: "Attemps count"
  highest: "Highest"
  result: "Result"
  time_limit: "Time limit"
  status_new: "Not started"
  status_checking: "Checking"
  status_passed: "Passed"
  status_failed: "Not passed"
  status_inprogress: "In progress"
  latest: "Latest"
  forbidden: "Forbidden"
  status_completed: "Completed"
  completed: "Completed"
  new: "New"
  about_bot: "Hi! I am a chatbot - personal assistant in the world of distance learning. With me, training becomes more accessible and interesting. Where do we start?"
  company: "Company"
  accounts: "Accounts"
  not_found: "Not found"
  choose_account: "Choose account"
  message: "Message"
  sent: "Sent"
  file: "File"
  page: "Page"
  show_less: "Show less"
  studying: "Studying"
  text: "Text"
  documents: "Documents"
  common_folder: "Common folder"
  incoming: "Incoming"
  creation_info: "I was created by <a href='https://sun1-93.userapi.com/c639318/v639318312/33bab/rbFlIllggaM.jpg'> Alexander Leskov </a> - @alexleskov from <a href = 'https: // teachbase.ru '> Teachbase </a> in 2020. And the idea of my appearance arose as an experiment - to create an assistant in online learning.\n\nSpecial thanks to Alexander Shvaikin - @shuriksh, for help with setting up the deployment and infrastructure."
  enter_what_find: "Clarify what you need. Keyword or phrase"
  notify_about_new: "You are waiting for a new"
  find_again: "Find again"
  demo_mode: "Demo mode"
  send_contact: "Send contact"
  click_to_send_contact: "Click on the button in the menu to share your contacts."
  notice_about_safety: "It is safe and will only be used for registration. Honestly."
  enter_by_auth_data: "Log in by entering your username and password yourself or reset password."
  meet_with_bot: "Let's get acquainted!"
  about_bot_demo_mode: "My name is <a href='https://storage.yandexcloud.net/tbpublic/other/2868-300x300.png'>Teachbaser</a> - I am a Telegram bot, your assistant in teaching on the Teachbase platform.\n\nTake courses, study the library of available documents - all this is right here in Telegram. With me you will not miss a new assigned course - I will send a notification. , I can perform many other useful functions. Learn more: /help.\n\nLet's start acquaintance? Select the item of interest below:"
  timeout: "Timeout of waiting for a response from the user after 30 seconds."
  reset_password: "Reset password"
  password_changed: "Password changed"
  help_info: "In addition to using the buttons in the menu, I can respond to text commands:\n\n1. Do you need a specific course? Write: \"Find a course \"or\" Recommend a course\" and a keyword or phrase.\n\n2 . If you have a technical question or you need to contact the curator, write \"Connect\" or \"Switch\", and then, who is needed - technical support or a tutor.\n\n3. To show the list of courses under study or already taken, write \"Show\" and then what. For example, \"Show active courses\".\n\n4. To view the profile of another student and the ability to write to him - enter the command \"/u[user id]\". For example \"/u97813\". The user ID can be found by opening your profile, via the button in the menu."
  start_time_has_not_come: "The start date has not yet arrived. Access will not open until a specified date and time."
  about_courses_page: "Here you can go to the current courses on the passage or see those that have already been completed. Click on the \"On study\", and then, in the list, go to the course with the name \"Demo course\"."
ru:
  greeting_message: "Привет,"
  farewell_message: "Пока"
  start_menu_message: "<i>Что делаем дальше?</i>"
  thanks: "Спасибо"
  sign_in: "Вход"
  more_actions: "Еще"
  settings: "Настройки"
  settings_list: "Настройки"
  hide_menu: "[Скрыть меню]"
  add_user_login: "Введите <b>ЛОГИН</b> (email/номер телефона)"
  add_user_password: "Введите <b>ПАРОЛЬ</b>"
  new_password_condition: "Новый пароль должен содержать не менее 6 символов"
  not_correct_email: "Это не email."
  error: "Ошибка"
  auth_failed: "Неправильный логин или пароль."
  try_again: "Попробуйте еще раз"
  greetings: "Добро пожаловать"
  auth_success: "Вход выполнен успешно"
  not_correct_data_input: "Введены неверные данные."
  teachbase: "Teachbase"
  retry: "Попытка подключения"
  cs_active: "на изучении"
  cs_archived: "завершенные"
  average_score_percent: "Качество освоения обучения"
  total_time_spent: "Общее время затраченное на обучение"
  courses: "Курсы"
  hour: "ч."
  minutes: "мин."
  profile_state: "Прогресс твоего профиля"
  profile: "Профиль"
  user_profile: "Профиль"
  need_auth: "Требуется авторизация"
  for_profile: "профиля"
  stage_empty: "Пока что здесь пусто"
  enter: "Войти"
  cs_list: "Список курсов"
  show_course_list: "Показать список курсов"
  course: 'Курс'
  cs: 'Курс'
  open: "Перейти"
  course_results: "Результаты"
  deadline: "Дата окончания"
  progress: "Прогресс прохождения"
  started_at: "Дата начала"
  success: "Успешность прохождения"
  status: "Статус завершенности"
  state: "Статус"
  success_true: "Успешно"
  success_false: "Не успешно"
  status_active: "На изучении"
  status_archived: "Завершен"
  section: "Раздел"
  section2: "разделов"
  section_show_hint: "Например, [id:1] - открыть Раздел №1"
  in: "в"
  information: "Информация"
  course_sections: "Содержание"
  update_data: "Обновить данные"
  updating_data: "Загрузка. Подождите"
  updating_success: "Загрузка данных прошла успешно"
  section_unable: "Станет доступно после прохождения предыдущих разделов"
  section_delayed: "Доступ откроется:"
  section_unpublish: "Не опубликовано"
  material: "Материал"
  empty: "Здесь ничего нет"
  cs_update: "Обновить список курсов"
  sign_out: "Выход"
  unexpected_error: "Неожиданная ошибка"
  scenario: "Режим обучения"
  base: "Базовый"
  localization: "Язык"
  show_all: "Все"
  show_avaliable: "Доступные"
  show_unvaliable: "Не доступные"
  show_all_sections: "Все разделы"
  show_avaliable_sections: "Доступные разделы"
  show_unvaliable_sections: "Не доступные разделы"
  from: "из"
  avaliable: "Доступно"
  section3: "разделов"
  find_by_query_num: "Найти по №"
  find_by_query_num_sections: "Найти раздел по №"
  enter_the_number: "Введите номер"
  edit: "Изменить"
  editing_settings: "Изменение настроек"
  editted: "Изменено"
  standart_learning: "Обычный"
  marathon: "Марафон"
  ru: "Русский"
  en: "Английский"
  choose_localization: "Выберите язык интерфейса"
  choose_scenario: "Выберите режим обучения"
  back: "Назад"
  forward: "Вперед"
  show_more: "Показать еще"
  courses2: "курсов"
  materials: "Материал"
  tasks: "Задание"
  quizzes: "Тест"
  quiz: "Тест"
  scorm_packages: "SCORM задание"
  content: "Контент"
  open: "Открыть"
  back_to: "Вернуться к"
  approve: "Подтвердить"
  view: "Просмотр"
  viewed: "Просмотрено"
  send: "Отправить"
  answer: "Ответ"
  task: "Задание"
  attachments: "Вложения"
  enter_your_answer: "Отправьте боту то, что хотите. Это может быть всё, что угодно – текст, фото, видео, аудио, документ (не более 5 МБ)"
  confirm_action: "Подтвердите действие"
  accept: "Подтвердить"
  decline: "Отменить"
  accepted: "Принято"
  declined: "Отменено"
  show: "Показать"
  answers: "Ответы"
  comments: "Комментарии"
  comment: "Комментарий"
  commented: "Прокоментировал"
  stop: "Стоп"
  ready: "Готово"
  enter_your_next_answer: "Продолжайте отправлять боту сообщения. Или нажмите на кнопку в меню"
  checking: "На проверке"
  undefined_action: "Ой! С этим я еще не умею работать :( Но скоро научусь!"
  undefined_text: "Ой! Не понял что нужно... Перефразируй?"
  undefined_file: "О, файл. Спасибо, но он мне пока не требуется :)"
  undefined_contact: "Настройки для связи с этим контактом еще не установлены."
  battle: "Сражение"
  description: "Описание"
  categories: "Категории"
  questions_count: "Кол-во вопросов"
  passing_grade: "Проходной балл"
  attempts: "Кол-во попыток"
  highest: "Наилучший"
  result: "Результат"
  time_limit: "Время на прохождение"
  status_new: "Не начато"
  status_checking: "На проверке"
  status_passed: "Пройдено"
  status_failed: "Не пройдено"
  status_inprogress: "В прохождении"
  latest: "Последний"
  forbidden: "Доступ закрыт"
  completed: "Пройдено"
  status_completed: "Пройдено"
  new: "Новый"
  about_bot: "Привет! Я чат-бот — личный помощник в мире дистанционного обучения. Со мной обучение становится доступнее и интереснее. С чего начнем?"
  company: "Организация"
  accounts: "Аккаунты"
  not_found: "Не найдено"
  choose_account: "Выберите аккаунт"
  message: "Сообщение"
  sent: "Отправлено"
  file: "Файл"
  page: "Страница"
  show_less: "Показать меньше"
  studying: "Обучение"
  text: "Текст"
  documents: "Документы"
  common_folder: "Общая папка"
  incoming: "Входящее"
  creation_info: "Меня создал <a href='https://sun1-93.userapi.com/c639318/v639318312/33bab/rbFlIllggaM.jpg'>Александр Лесков</a> - @alexleskov из <a href='https://teachbase.ru'>Teachbase</a> в 2020 году. А идея моего появления возникла как эксперимент - создать помощника в онлайн-обучении.\n\nОтдельная благодарность Александру Швайкину - @shuriksh, за помощь с настройкой деплоя и инфраструктуры."
  enter_what_find: "Уточните, что нужно. Ключевое слово или словосочетание"
  notify_about_new: "Тебя уже ждет новое"
  find_again: "Поискать еще"
  demo_mode: "Демо-режим"
  send_contact: "Отправить контакты"
  click_to_send_contact: "Нажмите на кнопку в меню, чтобы поделиться своими контактами."
  notice_about_safety: "Это безопасно и нужно только для регистрации. Честное слово."
  enter_by_auth_data: "Выполнить вход введя логин и пароль самостоятельно или сбросьте пароль."
  meet_with_bot: "Давайте познакомимся!"
  info_about_setted_password: "Похоже, что вы уже были зарегистрированы в системе ранее с таким номером телефона."
  about_bot_demo_mode: "Меня зовут <a href='https://storage.yandexcloud.net/tbpublic/other/2868-300x300.png'>Teachbaser</a> - я Telegram-бот, твой помощник в обучении на платформе Teachbase.\n\nПроходи курсы, изучай библиотеку доступных документов - все это прямо здесь, в Telegram. Со мной ты не пропустишь новый назначенный курс - я пришлю уведомление. Кроме этого, умею выполнять много других полезных функций. Узнать подробнее: /help.\n\nНачнем знакомство? Выбирай ниже интересующий пункт в меню."
  timeout: "Таймаут времени ожидания ответа от пользователя спустя 30 секунд."
  reset_password: "Сбросить пароль"
  password_changed: "Пароль изменен"
  help_info: "Помимо управления через кнопки в меню, я умею реагировать на текстовые команды:\n\n1. Нужен какой-то определенный курс? Напиши: \"Найди курс\" или \"Порекомендуй курс\" и ключевое слово, либо словосочетание.\n\n2. Если есть технический вопрос или нужно обратиться к куратору, напиши \"Соедини\" или \"Переключи\", а затем, кто нужен - техподдержка или куратор обучения.\n\n3. Чтобы показать списоку курсов на изучении или уже пройденные, напиши \"Покажи\", а затем что. Например, \"Покажи активные курсы\".\n\n4. Для просмотра профиля другого ученика и возможности ему написать - введи команду \"/u[id пользователя]\". Например \"/u97813\". ID пользователя можно узнать открыв свой профиль, через кнопку в меню."
  start_time_has_not_come: "Доступ не откроется до указанной даты и времени начала обучения."
  about_courses_page: "Здесь можно перейти к текущим курсам на прохождении или посмотреть те, которые уже завершились. Нажми на кнопку \"На изучении\", а затем, в списке, перейди в курс с названием \"Демонстрационный курс\"."